db:
  dsn: "root:root@tcp(localhost:13316)/webook_article"

redis:
  addr: "localhost:6379"

grpc:
  server:
    #  启动监听 8090 端口，你如果启动很多个服务的话，小心端口冲突
    addr: ":8097"
  client:
    user:
      addr: ":8091"