// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitee.com/geekbang/basic-go/webook/follow/events"
	"gitee.com/geekbang/basic-go/webook/follow/grpc"
	"gitee.com/geekbang/basic-go/webook/follow/ioc"
	"gitee.com/geekbang/basic-go/webook/follow/repository"
	"gitee.com/geekbang/basic-go/webook/follow/repository/cache"
	"gitee.com/geekbang/basic-go/webook/follow/repository/dao"
	"gitee.com/geekbang/basic-go/webook/follow/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *App {
	client := ioc.InitEtcdClient()
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	followRelationDao := dao.NewGORMFollowRelationDAO(db)
	cmdable := ioc.InitRedis()
	followCache := cache.NewRedisFollowCache(cmdable)
	followRepository := repository.NewFollowRelationRepository(followRelationDao, followCache, loggerV1)
	followRelationService := service.NewFollowRelationService(followRepository)
	followServiceServer := grpc.NewFollowRelationServiceServer(followRelationService)
	server := ioc.InitGRPCxServer(client, followServiceServer, loggerV1)
	saramaClient := ioc.InitSaramaClient()
	consumer := events.NewFollowConsumer(saramaClient, loggerV1, followRepository)
	app := &App{
		server:    server,
		consumers: consumer,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMFollowRelationDAO, cache.NewRedisFollowCache, repository.NewFollowRelationRepository, service.NewFollowRelationService, grpc.NewFollowRelationServiceServer)

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitRedis, ioc.InitSaramaClient, ioc.InitEtcdClient)
