db:
  dsn: "root:root@tcp(localhost:13316)/webook"
grpc:
  #  启动监听 9000 端口
  server:
    addr: ":8076"
    etcdTTL: 60
  client:
    feed:
      target: "etcd:///service/follow"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"
kafka:
  addrs:
    - "localhost:9094"