// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"gitee.com/geekbang/basic-go/webook/payment/ioc"
	"gitee.com/geekbang/basic-go/webook/payment/repository"
	"gitee.com/geekbang/basic-go/webook/payment/repository/dao"
	"gitee.com/geekbang/basic-go/webook/payment/service/wechat"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitWechatNativeService() *wechat.NativePaymentService {
	wechatConfig := ioc.InitWechatConfig()
	client := ioc.InitWechatClient(wechatConfig)
	gormDB := InitTestDB()
	paymentDAO := dao.NewPaymentGORMDAO(gormDB)
	paymentRepository := repository.NewPaymentRepository(paymentDAO)
	loggerV1 := ioc.InitLogger()
	nativePaymentService := ioc.InitWechatNativeService(client, paymentRepository, loggerV1, wechatConfig)
	return nativePaymentService
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitLogger, InitTestDB)

var wechatNativeSvcSet = wire.NewSet(ioc.InitWechatClient, dao.NewPaymentGORMDAO, repository.NewPaymentRepository, ioc.InitWechatNativeService, ioc.InitWechatConfig)
