db:
  dsn: "root:root@tcp(localhost:13316)/webook"

redis:
  addr: "localhost:6379"

kafka:
  addr: "localhost:9094"

grpc:
#  启动监听 8090 端口
  port: 8092
  etcdTTL: 60

etcd:
  endpoints:
    - "localhost:12379"